export const offerAdapter = (hotel) => ({
  bedrooms: hotel.bedrooms,
  city: hotel.city,
  description: hotel.description,
  goods: hotel.goods,
  host: hotel.host,
  id: hotel.id,
  images: hotel.images,
  isFavorite: hotel.is_favorite,
  isPremium: hotel.is_premium,
  location: hotel.location,
  maxAdults: hotel.maxAdults,
  previewImage: hotel.preview_image,
  price: hotel.price,
  rating: hotel.rating,
  title: hotel.title,
  type: hotel.type,
});
